"""
test_planner.py - Automated verification tests for the Route Planner & Web Application.
Verifies algorithm optimality, search pruning, Haversine calculations, and compliance with visual design standards.
"""

import json
import math
import re
from pathlib import Path
import pytest

from router import astar, dijkstra, haversine, load_campus_graph, snap_to_node

BASE_DIR = Path(__file__).resolve().parent
PUBLIC_DIR = BASE_DIR / "public"


def test_haversine_formula():
    """Verify that Haversine distance is 0 for identical points and accurate for real locations."""
    assert math.isclose(haversine(13.6288, 78.5024, 13.6288, 78.5024), 0.0, abs_tol=1e-5)

    # Bangalore to Chennai is approximately 290 km
    dist = haversine(12.9716, 77.5946, 13.0827, 80.2707)
    assert 280_000 < dist < 300_000


def test_optimality_astar_vs_dijkstra():
    """Verify that A* and Dijkstra find the exact same optimal path distance."""
    G = load_campus_graph()
    nodes = list(G.nodes())
    start = nodes[0]
    goal = nodes[len(nodes) // 2]

    dist_dijkstra, path_d, _, _ = dijkstra(G, start, goal)
    dist_astar, path_a, _, _ = astar(G, start, goal)

    assert dist_dijkstra is not None
    assert dist_astar is not None
    # Distance must match down to small float tolerance
    assert math.isclose(dist_dijkstra, dist_astar, rel_tol=1e-3)


def test_astar_search_pruning():
    """Verify that A* expands fewer or equal nodes compared to uninformed Dijkstra."""
    G = load_campus_graph()
    nodes = list(G.nodes())
    start = nodes[0]
    goal = nodes[-1]

    _, _, nodes_d, _ = dijkstra(G, start, goal)
    _, _, nodes_a, _ = astar(G, start, goal)

    assert nodes_a <= nodes_d, f"A* expanded {nodes_a} which is greater than Dijkstra {nodes_d}"


def test_identity_route():
    """Routing from a node to itself must immediately return 0 distance and 1 node."""
    G = load_campus_graph()
    sample_node = list(G.nodes())[0]

    dist, path, nodes_count, _ = astar(G, sample_node, sample_node)
    assert dist == 0.0
    assert path == [sample_node]
    assert nodes_count == 1


# --- Compliance & Anti-Pattern Verification Tests ---

def test_privacy_and_terms_pages_exist():
    """Verify that Privacy Policy and Terms of Service pages exist and are well-formed."""
    privacy_file = PUBLIC_DIR / "privacy.html"
    terms_file = PUBLIC_DIR / "terms.html"

    assert privacy_file.exists(), "privacy.html is missing"
    assert terms_file.exists(), "terms.html is missing"

    privacy_content = privacy_file.read_text(encoding="utf-8")
    terms_content = terms_file.read_text(encoding="utf-8")

    assert "Privacy Policy" in privacy_content
    assert "Terms of Service" in terms_content


def test_custom_favicon_present():
    """Verify that custom SVG favicon is present and referenced."""
    favicon_file = PUBLIC_DIR / "favicon.svg"
    assert favicon_file.exists(), "favicon.svg is missing"

    svg_content = favicon_file.read_text(encoding="utf-8")
    assert "<svg" in svg_content
    assert "</svg>" in svg_content

    index_html = (PUBLIC_DIR / "index.html").read_text(encoding="utf-8")
    assert 'rel="icon"' in index_html and "favicon.svg" in index_html


def test_no_ai_anti_patterns():
    """Verify absence of AI styling tells, sparkles, em dashes, and generic marketing tags."""
    index_html = (PUBLIC_DIR / "index.html").read_text(encoding="utf-8")
    css_content = (PUBLIC_DIR / "style.css").read_text(encoding="utf-8")
    privacy_html = (PUBLIC_DIR / "privacy.html").read_text(encoding="utf-8")
    terms_html = (PUBLIC_DIR / "terms.html").read_text(encoding="utf-8")

    all_html = f"{index_html} {privacy_html} {terms_html}"

    # 1. No "Made with AI" or platform branding tags
    assert "Made with AI" not in all_html
    assert "Powered by AI" not in all_html
    assert "Generated by" not in all_html

    # 2. No AI sparkle emojis
    assert "✨" not in all_html

    # 3. No em dashes in the copy
    assert "—" not in all_html

    # 4. No purple gradient classes / variables in CSS
    assert "purple" not in css_content.lower()
    assert "linear-gradient" not in css_content

    # 5. Buttons should not be pill-shaped (border-radius 9999px)
    assert "9999px" not in css_content
